name: Run get_all_ips script every 6 hours starting from 3:15

on:
  schedule:
    - cron: '*/6 * * * *'  # 每6分钟运行一次

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5  # 使用最新稳定版本

    - name: Set up Python
      uses: actions/setup-python@v5  # 使用最新稳定版本
      with:
        python-version: '3.x'  # 指定Python版本，可以根据需要调整

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run get_all_ips.py script
      run: python get_all_ips.py  # 替换成你的Python脚本文件名，确保包含了获取IP地址并写入IP.ini文件的逻辑
        
    - name: Commit IP.ini
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git pull origin main  # 拉取远程主分支的最新更新
        git add IP.ini
        git commit -m 'Update IP.ini with new IP addresses'
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/Zougmzz/MagiskOnWSA.git main
