name: 测试更新 IP 地址

on:
  schedule:
    - cron: '*/6 * * * *'  # 每6分钟运行一次

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run get_all_ips.py script
      run: python get_all_ips.py
        
    - name: Commit IP.ini
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git pull origin main
        git add IP.ini
        git commit -m 'Update IP.ini with new IP addresses'
        git push origin main --force
